development:
  aws_access_key_id: '18590ZXJ05SFT0CQ66R2'
  aws_secret_access_key: 'fYtPW48T2MvIqcwrcNOetyouSTY/G89+NGNxFpQN'
  bucket: 'tribute_development'

staging:
  aws_access_key_id: '18590ZXJ05SFT0CQ66R2'
  aws_secret_access_key: 'fYtPW48T2MvIqcwrcNOetyouSTY/G89+NGNxFpQN'
  bucket: 'tribute_staging'

production:
  aws_access_key_id: '18590ZXJ05SFT0CQ66R2'
  aws_secret_access_key: 'fYtPW48T2MvIqcwrcNOetyouSTY/G89+NGNxFpQN'
  bucket: 'tribute_production'

