development:
  key:    'hyFW4bDoZWUCKIe4pBv5Q'
  secret: 'pi3hZi5S0jkMTMksoV4m7HNLcIS2SHxacNO6Dr8iCM'

staging:
  key:    'hyFW4bDoZWUCKIe4pBv5Q'
  secret: 'pi3hZi5S0jkMTMksoV4m7HNLcIS2SHxacNO6Dr8iCM'

production:
  key:    'Mp3vPtsrDF51Tev8xRJ4wg'
  secret: 'Fjgqdya208evFe5PRec2pzlB3WCoUapw7R5Rg7qlGM'
